name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install Root Dependencies
        run: yarn install
      - name: Check Types
        run: yarn lint:types
      - name: Lint HBS
        run: yarn lint:hbs
      - name: Lint JS
        run: yarn lint:js
  basic-tests:
    name: Basic Tests
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Basic Development Tests
        run: yarn test:development
      - name: Basic Production Tests
        run: yarn test:production
