name: Enforce Canary PR labeling

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]
    branches:
      - main

concurrency:
  group: pr-labels-canary-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-changelog-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: ':memo: breaking,:memo: feat,:memo: bugfix,:memo: perf,:memo: cleanup,:memo: deprecation,:memo: infra,:memo: doc,:memo: test,:memo: chore,:memo: skip'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label for changelog generation. Use the label `:memo: skip` and none of the others in the list to avoid this being included. [':memo: breaking', ':memo: feat', ':memo: bugfix', ':memo: perf', ':memo: cleanup', ':memo: deprecation', ':memo: doc', ':memo: infra', ':memo: test', ':memo: chore', ':memo: skip']"
  enforce-target-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: 'target:canary,target:release'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label for what release channels to target. Use the label `target:canary` and none of the others in the list if this PR should not be backported. ['target:canary', 'target:release']"
  ban-release-branch-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          BANNED_LABELS: 'backport-release'
          BANNED_LABELS_DESCRIPTION: "The following labels should only be applied to PRs targeting release channel branches that backport a change already on the master branch, remove them.['backport-release']"
